### ISSUE TITLE
new File fails on ie 11.0.15 / safari

### ISSUE THREAD

**Issue by jony89** [jimmywarting/FormData#11]
The following line will fail on ie : 

```js
value = new File([value], filename
```

gives 

> Object doesn't support this action

as it doesn't have a constructor in IE

**Comment by jimmywarting** [comment]
Browser version?

**Comment by jony89** [comment]
i wrote.. ie 11.0.15 but it will occur on any IE.

**Comment by jimmywarting** [comment]
hmm, ie don't support the file constructor... 😕 

> Does not support the File constructor
http://caniuse.com/#feat=fileapi

**Comment by jony89** [comment]
Yeah, it should be fixed though. as this is a polyfill :)

**Comment by jimmywarting** [comment]
I think we could do something like this:


```js
let File = window.File

try {
  new File([], '')
} catch(e) {
  File = class File extends Blob {
    constructor(chunks, filename, opts = {}){
      super(chunks, opts)
      this.name = filename
    }
  }
}
```

**Comment by jony89** [comment]
what about using `Blob` directly ? or maybe `FileReader` could be solution as well.

the above seems fragile lil bit ..

**Comment by jony89** [comment]
example : http://stackoverflow.com/questions/33821631/alternative-for-file-constructor-for-safari

**Comment by jony89** [comment]
sure,

it works though it sends a BLOB to the server thus failing on server side. 

I think this reproduced as well on safari, isn't ?
