### ISSUE TITLE
Not IE Safe

### ISSUE THREAD

**Issue by rcampbel** [jimmywarting/FormData#115]
The [Method Definitions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) used in the code are not IE safe.

Example:
https://github.com/jimmywarting/FormData/blob/18479550bebb79ae76c39cf23c2694619463170f/FormData.js#L57-L59

**Comment by rcampbel** [comment]
Also the use of `const` and `let` are not supported until ie11

**Comment by chhatch** [comment]
Use formdata.min.js instead. `const` and `let` are not used there.

**Comment by jimmywarting** [comment]
☝️  what he said
