### ISSUE TITLE
error TS2322: Type 'FormData' is not assignable to type 'BodyInit'.

### ISSUE THREAD

**Issue by israelidanny** [jimmywarting/FormData#133]
Using `FormData` with `node-fetch@3.0.0` results in the following error:
```
error TS2322: Type 'FormData' is not assignable to type 'BodyInit'.
  Property 'sort' is missing in type 'FormData' but required in type 'URLSearchParams'.
```

**Comment by jimmywarting** [comment]
Hmm, FormData don't have a sort method... think this might be an issue with node-fetch

`new URLSearchParams().sort` exists but this formdata don't have anything to do with URLSearchParams...
