### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by morettisf** [jimmywarting/FormData#15]
Hi, I'm having trouble finding a way to get this to work. Do you need to 'require' it in as a certain variable at the top of your js file or does it automatically run? 

Can you give an example of a use case with .append() a file and object with sending xhr? Do I need to assemble and send a Blob? If so, I'm not sure how to create this Blob.

Sorry, struggling to understand the documentation.

**Comment by jimmywarting** [comment]
Yea, you need to require it
```js
const FormData = require('formdata-polyfill')
// import FormData from 'formdata-polyfill'

let fd = new FormData(form)
let blob = new Blob(['abc'], {type: 'text/plain'})

fd.append('file', blob, 'sample.txt')
fetch('/upload', {method: 'post', body: fd._blob()})
  .then(res => console.log(res.ok))
```

**Comment by morettisf** [comment]
OK still having trouble. FYI I'm not trying to pass in a form, though here is the snippet I'm working with. "logData" is an object. Can you advise?

```
var f = new FormData(form)

let blob = new Blob('logData', JSON.stringify(logData))
f.append(blob)

f.append('pics', document.querySelector('#file1').files[0])
f.append('pics', document.querySelector('#file2').files[0])
f.append('pics', document.querySelector('#file3').files[0])
f.append('pics', document.querySelector('#file4').files[0])
f.append('pics', document.querySelector('#file5').files[0])

var xhr = new XMLHttpRequest()
xhr.open('post', '/create-log')
xhr.send(f._blob())
```

**Comment by jimmywarting** [comment]
What is shown in the console log?

**Comment by morettisf** [comment]
This is iOS Safari FYI
