### ISSUE TITLE
Boundary includes uppercase. Chrome always lowercases Blob.type.

### ISSUE THREAD

**Issue by d11wtq** [jimmywarting/FormData#17]
I'm running into issues using this Polyfill to upload files in Chrome (possibly all WebKit). The server (a Rack server in Ruby) complains that the response is invalid, since it cannot find any multipart boundaries. A `EOFError` is raised during request body parsing.

It turns out this is due to the following code:

https://github.com/jimmywarting/FormData/blob/master/FormData.js#L227

Which looks completely correct to me, however, in Chrome this causes the request body to use uppercase + lowercase characters, while the actual content type of the generated Blob is forced to lowercase, thus producing an invalid request. I was able to fix this by simply patching FormData to only use a lower case boundary.

Notice the `console.log` output of the Blob itself and the contents of the Blob.

![image](https://cloud.githubusercontent.com/assets/37948/24388669/e5de7df4-13c7-11e7-8c71-389a4b4a0641.png)

**Comment by d11wtq** [comment]
See #18.

**Comment by mryellow** [comment]
Frankly this MUST be a bug in the specs. They shouldn't be messing with the case of header content.

Can't believe no one else has noticed.
