### ISSUE TITLE
This lib contains const and arrow function

### ISSUE THREAD

**Issue by homs44** [jimmywarting/FormData#20]
I use this formdata and webpack2. 
When I build my application with webpack, the message "unexpaced token (>) " is show up. 
and I realize that this library contains const and array function, so I have to add additional code to webpack.

        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules(?!\/formdata-polyfill)/,    <-- here 
                use: [{
                    loader: 'babel-loader',
                    options: {
                        presets: [['es2015', {modules: false}], 'react'],
                        plugins: ["syntax-dynamic-import"]

                    },
                }]

            },

**Comment by jimmywarting** [comment]
I put a minified version up on npm from closure compiler that is now used by default

all stuff are es5
