### ISSUE TITLE
SyntaxError in IE11

### ISSUE THREAD

**Issue by julmot** [jimmywarting/FormData#22]
Using the polyfill failed for me in IE11:

![2017-08-09 18_34_34-de sede frontend component library - internet explorer](https://user-images.githubusercontent.com/8310677/29132739-72aafb7c-7d31-11e7-88d4-f19fa49fb148.png)

**Comment by jimmywarting** [comment]
Only have mac, so it's a bit hard for me to test

**Comment by julmot** [comment]
Just use BrowserSync or Saucelabs.

**Comment by anddoutoi** [comment]
@julmot or even better… "just" debug, fix and make a PR.

**Comment by julmot** [comment]
Why don't you do this yourself? And who the fuck are you? 😆

**Comment by cheeaun** [comment]
@julmot is it possible to create a simple demo page to reproduce this bug? It's difficult to pinpoint the problem when the error is cryptic and there's no steps to reproduce this error.

**Comment by r3dcrosse** [comment]
@jimmywarting If you want to test IE/Edge on a Mac, I recommend using some kind of Virtual Machine software and the [free virtual machines from Microsoft.](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)

@julmot I'm having difficulty reproducing your error in IE11. Is it possible that error is coming from something else in your scripts.js bundle? If it is coming from the FormData polyfill, what were the steps you took that caused that error?

**Comment by julmot** [comment]
Unfortunately I can't. I've tried to create a sample but experiencing another bug: The plugin seems to relay on `module`, which isn't available in JSFiddles...

![2017-08-27 19_50_35-create a new fiddle - jsfiddle](https://user-images.githubusercontent.com/8310677/29752580-26638eda-8b61-11e7-8cc5-b85dfd19f43b.png)

However, with this HTML as a starting point you should be able to reproduce the other bug:

https://jsfiddle.net/qzbuhr5h/

**Comment by jimmywarting** [comment]
it's the way you load the plugin which is failing, I have only made it available with a modular loader. you can't directly include the file in a browser
