### ISSUE TITLE
Shim global?

### ISSUE THREAD

**Issue by stevenvachon** [jimmywarting/FormData#24]
Would be convenient.

```js
if (typeof window.FormData ==='undefined' || typeof window.FormData.prototype.get === 'undefined') {
  window.FormData = FormDataPolyfill;
}
```

**Comment by jimmywarting** [comment]
If I would do so, I would have to patch both xhr & fetch as well.
For example:

```js
var send = XMLHttpRequest.prototype.send

XMLHttpRequest.prototype.send = function(data) {
  send.call(this, data instanceof polyfill ? data._blob() : data)
}
```

Don't feel so comfortable doing it. Has to be executed in the right order before [xdomain](https://github.com/jpillora/xdomain) or after [fetch polyfill](https://github.com/github/fetch/issues)
This is enough of a maintenance headache.

I feel like this is it's solo purpose of being a grate FormData polyfill and that other modules are responsible for using it correctly. I have already sticked my nose where it don't belongs in to patching the File constructor. Not sure if it was the right thing to do, but only cuz FormData was using it and i wanted it to look as close to the real thing as possible.

The effect of it was that a file is not a instance of File, see this example:

```js
  var nativeExampleFileFromInput = new File('foo', ['foo.txt'])

  // Patch for ie/safari/edge that returns a Blob
  window.File = function (b, d, c) {
    var blob = new Blob(b, c)
    var t = c && void 0 !== c.lastModified ? new Date(c.lastModified) : new Date

    Object.defineProperties(blob, {
      name: {
        value: d
      },
      lastModifiedDate: {
        value: t
      },
      lastModified: {
        value: +t
      },
      // make it resemble a File
      toString: {
        value: function () {
          return '[object File]'
        }
      }
    })

    // make it resemble a File
    if (window.Symbol && Symbol.toStringTag) {
      Object.defineProperty(blob, Symbol.toStringTag, {
        value: 'File'
      })
    }

    return blob
  }

  console.log(nativeExampleFileFromInput instanceof File) // false
  console.log(nativeExampleFileFromInput instanceof Blob) // true
  console.log(nativeExampleFileFromInput[Symbol.toStringTag] === 'File') // true
```

**Comment by jimmywarting** [comment]
But if others wants it, then I'm willing to reconsider

I would be more then willingly to references another modules that uses my polyfill to patch xhr/fetch

**Comment by jimmywarting** [comment]
Fixed, just have to publish it to npm first, will do that later...
Meanwhile I would appreciate if you could test it and also edit the readme.md before i publish it.

Thanks in advance and for using the formdata polyfill

**Comment by jimmywarting** [comment]
published on npm as v3
