### ISSUE TITLE
Not handling handling radios correctly? 🤔

### ISSUE THREAD

**Issue by johnboxall** [jimmywarting/FormData#25]
It _appears_ the compiled code does not handle radios correctly.

I've built a small test page to demonstrate the issue:

https://test-formdata-polyfill.surge.sh/

Open your browser's console and you'll see the output of two `FormData` instances created from the same form. One is built from the browser's native implementation and the other from the polyfill:

![image](https://user-images.githubusercontent.com/28967/29490493-f8aa7ebe-84f2-11e7-8dcb-b4a520d46fa5.png)

It appears the polyfill wants to submit all the radio inputs – even the unchecked ones!

The code used to create the test page is here:

https://github.com/johnboxall/test-formdata-polyfill

> Thanks so much for this module 🙏  – I was not expecting Mobile Safari to have such limited support for `FormData`. This repo saved us from a bunch of custom code!

**Comment by jimmywarting** [comment]
Related to #23
Forgot to publish the fix to npm, gona do it now

**Comment by jimmywarting** [comment]
Released new version
