### ISSUE TITLE
Blobs not being sent

### ISSUE THREAD

**Issue by velochy** [jimmywarting/FormData#26]
It seems that you normalize all Blob objects to File objects, but then in _blob() you check if they are still Blobs. The result (on Safari, at least) is that since File is not an instance of Blob, they get encoded as simple form fields i.e. their content does not get encoded.

The best way to solve this in my opinion is to not try to accommodate the native "File" option, but instead always use the File wrapper fallback that you have. Meaning, instead of using try/catch to check if native file is present, you always define "BlobWrapper" and use that to wrap the blobs - and not call it "File".

this also takes care of problems arising when other polyfills rewrite the functionality of File (which is the case for my deployment where File object is filled in by cordova-plugin-file), making it a lot safer and more widely applicable.

**Comment by jimmywarting** [comment]
PR are welcomed

**Comment by velochy** [comment]
Will try to put it together then if you conceptually agree with the
recommendation.

**Comment by velochy** [comment]
After a bit more digging, I realized the problem is not related to safari but cordova-plugin-file overloading the "File" definition to no longer be an instance of "Blob" and also screwing up the constructor to have File(name,content) instead of File(content,name) format.

To solve this without breaking the other uses, I would wrap Blobs into a BlobWrapper (that is what your "File" replacement is), keep Files as Files, and at the _blob() step check if either instanceof Blob or instanceof File.

However - this use case is probably too niche for you to worry about to be honest. Feel free to just close this thread for now.
