### ISSUE TITLE
polyfill looks good but no implementation in npm package manager

### ISSUE THREAD

**Issue by dareksob** [jimmywarting/FormData#3]

**Comment by jimmywarting** [comment]
Name suggestion?

**Comment by dareksob** [comment]
like your repo path ;-)

**Comment by jimmywarting** [comment]
if [formdata](https://www.npmjs.com/package/formdata) or [form-data](https://www.npmjs.com/package/form-data) wasn't taken i wouldn't have asked

**Comment by nielsvanmidden** [comment]
`formdata-polyfill` perhaps...
