### ISSUE TITLE
Before publishing v3, consider implementing the es-shim-api standard

### ISSUE THREAD

**Issue by tremby** [jimmywarting/FormData#31]
See https://github.com/es-shims/es-shim-api

It may be that this package isn't suitable for that API. But if it is, it'd be nice to follow it. The more polyfills which follow the same standard, the easier it is to remember how to use them all! It's annoying to use 6 or 7 different polyfills and have to instantiate them all in different ways...

**Comment by jimmywarting** [comment]
So what changes needs to be made exactly?

**Comment by tremby** [comment]
It's all detailed under "API Contract" on the readme I linked. I can't explain it better than they can!
