### ISSUE TITLE
Consider removing the minified JS

### ISSUE THREAD

**Issue by tremby** [jimmywarting/FormData#32]
You can generate this with a prepublish command in package.json so it's included on NPM without it having to be in the git repository.

See https://docs.npmjs.com/misc/scripts#use-cases

**Comment by jimmywarting** [comment]
Never done something with prepublish, PR is welcome to show me how it's made.
Guessing it should maybe call googles closure-compiler
API referens: https://developers.google.com/closure/compiler/docs/api-ref

Also what about when i want to make a [release](https://github.com/jimmywarting/FormData/releases) here on github then?

**Comment by tremby** [comment]
PR opened. See my comments there for changes you may want to make.

To answer your question about releases on Github, you can run `npm pack` to run the preparation logic (i.e. minify the JS) and produce a tarball. Or you could just not upload tarballs and let people download the zip Github provides associated with the tag and then run `npm install`, which would then install the dev dependency (closure compiler) and minify the JS.
