### ISSUE TITLE
Doesnt respect disabled attribute...

### ISSUE THREAD

**Issue by rejas** [jimmywarting/FormData#36]
Hi, when submitting a form with disabled select/input fields using this polyfill results in values from those disabled fields also being included in the formdata key/value pairs (with no way of filtering them out).

So:
`<input type="text" name="foo" value="isDisabled" disabled="disabled"/> `
doesnt show up in a normal FormData call (tested under Chrome) but using your polyfill it appears in the data :-(

**Comment by rejas** [comment]
using v2.0.4 still btw

**Comment by rejas** [comment]
testing v3 alpha right now....

**Comment by rejas** [comment]
Seems to work correctly in v3 but I'll let the QA department cofirm it :-)

**Comment by jimmywarting** [comment]
I just fixed it in v3.0.1

Wish you had made the issue 30 minutes earlier before i published v3.0.0 now it is v3.0.1 b/c of this :P

**Comment by rejas** [comment]
Murphys Law strikes again :-) (plus: never trust a .0 version :-D Thx for the quick fix!!!

**Comment by jimmywarting** [comment]
> never trust a .0 version

😆
