### ISSUE TITLE
<select /> emits "undefined" in entries()

### ISSUE THREAD

**Issue by clschnei** [jimmywarting/FormData#38]
Instead of using the `select` element's `"name"` in the tuples, the `constructor` is using the `option`'s `"name"`. This appears to be inconsistent with [the spec](https://xhr.spec.whatwg.org/#interface-formdata).

_Lines in question:_ https://github.com/jimmywarting/FormData/blob/59e46d05b70c9ea0db4d52ef4ccbbbc77afac3aa/FormData.js#L131-L133

**Comment by jimmywarting** [comment]
So it should be like this: `this.append(elm.name, opt.value)`?

**Comment by clschnei** [comment]
That's what I'm guessing. I actually forked the branch, and am in the middle of adding unit tests as well. 

Tried using `jest` but their current `jsdom` version doesn't implement `selectedOptions`. Trying to decide whether to mount the new version manually, or switch to karma + Chrome headless.

**Comment by jimmywarting** [comment]
I would love to have a unit test.
Karma seems like the best option. Since we are targeting real browsers.

**Comment by jimmywarting** [comment]
closed in daab62a9d4ca014757e2d0beb2c34f8ffa065e46
