### ISSUE TITLE
Not forcing FormData polyfill on all browsers

### ISSUE THREAD

**Issue by Aebrathia** [jimmywarting/FormData#41]
https://github.com/jimmywarting/FormData/blob/328c0cdc75dfdff24b603f664a7cef21e7fc3ff4/FormData.js#L1

Has this line been added purposefully or is it a remnant of local testing ? It makes all browsers use the polyfill.

Thanks

**Comment by jimmywarting** [comment]
I accidentally included it when i tested the code in a browser, it's removed

**Comment by jimmywarting** [comment]
removed
