### ISSUE TITLE
Edge/IE fail to set Content-Type header on XHR whose body is a typed Blob

### ISSUE THREAD

**Issue by balessan** [jimmywarting/FormData#44]
Hello Jimmy,

I am using your polyfill on my current project to be able to use the FormData object on IE 11, and it seems good until the request is actually processed by the server.

Working on a PHP back-end, when I var_dump the request Body I got something which looks like the following:

```
------formdata-polyfill-0.66513968191100183ContentDispositionform-dataname=emailben@toto.fr------formdata-polyfill-0.66513968191100183ContentDispositionform-dataname=password------
```

And so on. Obviously this body seems badly-formed.
I am using your polyfill by requiring it from my main JS entry file:

```js
require("formdata-polyfill");

window.app = new (function()
{
     ...
```

And to submit my form I am using the following code:

```js
if ( ! formData )
{
  var formData = new FormData( _.formInstance );
}

var xhr = new XMLHttpRequest();

xhr.open( method, url );

xhr.setRequestHeader( "X-Requested-With", "XMLHttpRequest" );

xhr.send( formData );
```

The content of formData is ok at this point ( I displayed the key value content to be sure ). So I am not sure of the source of the issue. Any Idea ?

It's blocking for me right now, as I cannot get the complete support of my app on IE 11...

Let me know ;-)

**Comment by jimmywarting** [comment]
hmm, it do look badly formatted. Could you try to dump the content using client side code?
here is how
```js
var blob = formdata._blob() 
var fr = new FileReader
fr.onload = function() {
  console.log(fr.result)
}
fr.readAsText(blob)
```

for me it looks something like: 
```
------formdata-polyfill-0.24730354822730538
Content-Disposition: form-data; name="key"

value
------formdata-polyfill-0.24730354822730538--
```
which is correct

**Comment by balessan** [comment]
Using the code you provided I got the following ( see the screenshot as I am testing using BrowserStack and cannot copy/paste easily ), which looks ok.

So then it's an issue on the backend side.Is that possible that the formdata-polyfill prefix is conflicting with the form entry parsing library of my current framework ?

 Hum...
![capture d ecran de 2017-12-03 15-30-31](https://user-images.githubusercontent.com/356084/33526310-81c15e08-d83f-11e7-86f2-131f65ff8cfe.png)

**Comment by jimmywarting** [comment]
Got to be a problem on the server side...
Are you using a library for parsing multipart forms?

Things you can check:
- Are the the blob size the same as `Content-Length` request header?
- Are the `Content-Type` request header same as the blob's mime type?

PHP should be able to parse it `$_POST["email"]`

**Comment by balessan** [comment]
I'll check that ;-)

**Comment by jimmywarting** [comment]
chromes FormData don't look much different
```js
fd = new FormData
fd.append('key', 'value')
new Response(fd).text().then(console.log)

result = `
------WebKitFormBoundary9F5Xu977y9H9FXm0
Content-Disposition: form-data; name="key"

value
------WebKitFormBoundary9F5Xu977y9H9FXm0--
`
```

**Comment by balessan** [comment]
What seems strange is that the developer tools of my IE11 borwserStack instance are not detecting anything in the request body, even though the code you gave me seems ok. See the following screen for reference.

It really looks to me that the HTTP Post is send empty.

![capture d ecran de 2017-12-03 15-57-15](https://user-images.githubusercontent.com/356084/33526501-d290ee18-d842-11e7-8cfe-4dae9c7d8fd8.png)

**Comment by jimmywarting** [comment]
I'm not sure how you can miss something like a `-`, `spaces` and `;` in your body. Something is stripping the content

**Comment by jimmywarting** [comment]
Weird. try sending the blob then and see what happens... `xhr.send(formdata._blob())`

**Comment by jimmywarting** [comment]
mather of fact, it looks to me like you are inspecting the response body, response header & the response content-type

**Comment by balessan** [comment]
Ok on the client side I was missing the Content-Type : multipart/form-data which explains the emptyness of the request body when inspecting.

Remaining issue is on the backend side.

Thanks for your attention, I have been making some progress ;-) And your library has no issue then.

**Comment by jimmywarting** [comment]
Was snooping around on browserstack myself when you reveled your website.
It doesn't look like the Content-Type is being set?

If you would perhaps do it like this:

var blob = formdata._blob();

xhr.open( method, url );
xhr.setRequestHeader( "X-Requested-With", "XMLHttpRequest" );
xhr.setRequestHeader( "Content-Type", blob.type );
xhr.send( blob );

would it work for you then?

**Comment by jimmywarting** [comment]
In that case i might make a patch where i set the content-type header in the polyfill

**Comment by balessan** [comment]
I am testing.

**Comment by jimmywarting** [comment]
The spec is: If you are sending a Blob/file with ajax and no content-type header is specified it should use the Files type as content-type. IE don't seems to follow that rule?

**Comment by balessan** [comment]
Yes I can confirm your patch works fine.

Stupid IE.

**Comment by jimmywarting** [comment]
Gah, hate IE. Going to make a patch to fix it.

**Comment by jimmywarting** [comment]
found something related: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6047383/

**Comment by balessan** [comment]
Top ! And reallym thanks for your time ;-)

**Comment by balessan** [comment]
I am not that familiar with the use of Blobs so I did not look in that direction but yeah, your article seems to correspond to the situation.

**Comment by jimmywarting** [comment]
Fixed in 3.0.6

**Comment by balessan** [comment]
:+1:

**Comment by balessan** [comment]
Tested but got an issue being:

```
Object does'nt support property or method 'a'
```
The incriminated line being:

```
XMLHttpRequest.prototype.send=function(b){b instanceof H&&(b=b.a(),this.setRequestHeader("Content-Type", b.type))
```

**Comment by jimmywarting** [comment]
Forgot closure compiler mangels private properties/methods starting with `_`
Fixed in 3.0.7

**Comment by balessan** [comment]
Works perfect !

**Comment by initialleaf821** [comment]
> I am testing.





https://overbearingpillowcase.github.io/M8CvefedH2YBO8LvHl/
