### ISSUE TITLE
Assign FormData fields back to form? Any interest?

### ISSUE THREAD

**Issue by jimmywarting** [jimmywarting/FormData#50]
I was thinking of building something new to do the reverse thing (unrelated to this polyfill).

eg. You make a FormData instance and append a bunch of things.
Since it's now readable/iterable you could then loop over all the FormData items and assign all the fields back to a from element

```html
<form>
  <input type="text" name="firstname">
  <input type="text" name="lastname">
</form>

<script>
  Object.defineProperty(HTMLFormElement.prototype, 'formData', {
    set(formData) {
      // loop over formData and append all values back to `this.elements`
    },
    get() {
      return new FormData(this)
    }
  })

  var form = document.querySelector('form')
  var fd = new FormData()
  fd.append('firstname',  'Bob')
  fd.append('lastname',  'Stone')

  form.formData = fd
  //  <input type="text" name="firstname"> would now have the value "Bob"
  //  <input type="text" name="lastname"> would now have the value "Stone"
</script>
```

Why?
=====
It could be a easy way of assigning many values back to a form element where editing preference for an existing user account needs to change lots of things.
It would save you the hassle of having to loop over each element and assign it manually (no mather what the DOM structure looks like)

**Note:** It's also possible to get a FormData instance using the fetch api for example. I did this hack to download multiple images once in one request. Didn't have to zip everything. server can send a multipart/form-data back also

```js
fetch('/settings')
  .then(res => res.formData())
  .then(fd => {...})
```

**Comment by anddoutoi** [comment]
I really like the gist of this idea. We sometimes (using React/Redux) store a full _FormData_ instance in the store and it would be very convenient if we could just take `props.formData` and apply it to a `<form>`. The contract would be very strong in this case. Now we do this in a custom way.

I'm not sure I like the _getter/setter_ approach and I generally prefer not to dabble with built-in prototypes even if it's supported by most UAs today. This operation could be "costly" and a function/method call shows this better then just a _setter_. Using a function also enables you to have an optional _iteratee_ handler if you need to make something custom.

I also guess that the scope needs to be limited to _static_ forms and the handling of dynamically added form controls and values can be considered in a 2.0.

**Comment by jimmywarting** [comment]
I wan't to built it independent of any framework (jQuery, Angular, React) so it can work in any project.

I'm still wondering if you sometimes need a custom iteratee handler. or if you need custom options
The way the it should work is doing the opposite thing to what `new FormData(form)` dose

I was also thinking what if the element don't exist? should it create a `<input type="hidden">` with it's value? or only assign it to dose element that dose exist.

**Comment by anddoutoi** [comment]
Agree on that is should be completely framework agnostic. I was just emphasising how we are using FormData (and by that, this polyfill).

> I was also thinking what if the element don't exist? should it create a <input type="hidden"> with it's value? or only assign it to the element that dose exist.

Kind of depends of the purpose of the feature. To fill in a form from a FormData object or make a 1-to-1 mapping for network transport?

In a first version I would say that it should not mutate the markup or try to do some "smart things".
