### ISSUE TITLE
How to use is in a worker?

### ISSUE THREAD

**Issue by renanbandeira** [jimmywarting/FormData#52]
I have some issues trying to make it useful while running on a webworker. Basically there is no window on a webworker context and it crashes on first if.

**Comment by jimmywarting** [comment]
maybe should have used self instead of window...
will figure out the best way to get the global variable

**Comment by jimmywarting** [comment]
Would you care to test the new minified version before i publish it to npm?

**Comment by PierreGUI** [comment]
The new version of the polyfill breaks where window isn't defined. This includes running in V8 engine (eg server side rendering of a React app).

I suggest you make sure to check whether `window` can be accessed.   
ie:`typeof window === "object"` or `typeof window !== 'undefined'`

**Comment by jimmywarting** [comment]
just need to publish it to npm. If it works correct i can do it now

**Comment by PierreGUI** [comment]
Using the latest master branch I don't run into the issue anymore 👍

**Comment by renanbandeira** [comment]
It's working as a charm! Thanks =D

**Comment by jimmywarting** [comment]
publish
