### ISSUE TITLE
Select elements where the option is both selected and disabled are included in FormData

### ISSUE THREAD

**Issue by andybflynn** [jimmywarting/FormData#56]
In Chrome, FF and Safari the FormData does not include `select` elements where the option value is both selected and disabled (e.g. `<option selected disabled value="0">Please choose one</option>`)

This is because these values should not be submitted with the form [as per the spec](https://www.w3.org/TR/html401/interact/forms.html#disabled).

Currently the polyfill behaviour is that it only checks the selected value of the option rather than checking the disabled value as well.

Can I suggest changing line 130 of FormData.js to the following?
`!opt.disabled && opt.selected && this.append(elm.name, opt.value)`

Cheers

**Comment by jimmywarting** [comment]
We'll probably be able to fix that. But I'm on a schedule now. have to take a raincheck later today

**Comment by jimmywarting** [comment]
Done!

**Comment by andybflynn** [comment]
Great work, thank you for actioning it so quickly!
