### ISSUE TITLE
FormData Object on IOS Safari sw worker

### ISSUE THREAD

**Issue by stebuklas** [jimmywarting/FormData#57]
On IOS, service worker side, when using fetch and sending `formData()` it sends it as `[FormData Object]`.

```js
fetch(url, {
  method: 'POST',
  body: formData,
  credentials: "same-origin",
  headers: {
    'X-Requested-With':'XMLHttpRequest'
  }
})
```

When sending `formData._blob`, it send file, but there is more items appended to formData Object.

Any workaround?

**Comment by jimmywarting** [comment]
I don't know much of what's going on and can't pinpoint the problem in your or my code but i can give you some help to debug the problem.

------

The hole solution to this polyfill is that it's going to send a file in the end... and call `formdata._blob()` itself [FormData.js#L376](https://github.com/jimmywarting/FormData/blob/master/FormData.js#L376)

Are you getting a references to native implementation or the patched fetch function when you `console.log(fetch)`?
the polyfill must be executed first to replace it... 

------

I don't know why you get fewer items appended but you can inspect what is appended and what not by doing this:

```js
var entries = formData.entries()
var iterator = entries.next()

while (!iterator.done) {
  console.log(iterator.value)
  entries.next()
}
```
Or with this:
```js
// Logs the raw body:
new Response(formdata._blob()).text().then(console.log)
```

-----

Calling `formdata._blob()` conditionally could potentially be a workaround: 
```js
fetch(url, {
  method: 'POST',
  body: formdata._blob ? formdata._blob() : formdata,
  credentials: "same-origin",
  headers: {
    'X-Requested-With':'XMLHttpRequest'
  }
})
```

----

Hopefully it should also set the requested `content-type` header to the correct value, hope we don't have the same problem as ie. (https://github.com/jimmywarting/FormData/issues/44) - might be irrelevant

**Comment by jimmywarting** [comment]
closing b/c of no further discussion
