### ISSUE TITLE
Error with fileform

### ISSUE THREAD

**Issue by Worka** [jimmywarting/FormData#60]
Hi!

I have form:

```
<form action="form_action" method="post>
    <input type="file" name="image" />
    <textarea name="reply"></textarea>
    <input type="hidden" name="submit" value="submit" />
</form>
```

And js-code:

`const data = new FormData(document.querySelector('form'));`

When I do submit, I get error

> file of elm.files is not a function

I use old iPad with safari version 602.1

**Comment by jimmywarting** [comment]
could you try to do this and see what you get:

```js
alert('files' in HTMLInputElement.prototype)
alert(typeof FileList)
```
