### ISSUE TITLE
Content-Type is application/json  , formdata not recognize on IE 11  and no data sended issue 

### ISSUE THREAD

**Issue by anwar101** [jimmywarting/FormData#61]
I updated to V3 and same issue occur with me when send angular http post request still
  Content-Type: application/json; charset=utf-8 and formdata not recognize on IE 11 

Please Advise

_Originally posted by @anwar101 in https://github.com/jimmywarting/FormData/issues/33#issuecomment-437969727_

**Comment by jimmywarting** [comment]
can you show some bit of code that you are making?
