### ISSUE TITLE
e.append is not a function

### ISSUE THREAD

**Issue by f0rmat1k** [jimmywarting/FormData#63]
Good day!

I'm getting a lot of errors in sentry:

> e.append is not a function.

It's always occurs in:
Chrome Mobile iOS Version: 70.0.3538
iOS Version: 10.3.3

stacktrace points at this

https://github.com/jimmywarting/FormData/blob/f18bd6e8dbea9e520cdd0d98f539c520a236cee0/FormData.js#L142

Unfortunately, i don't have device on 10.3.3 but maybe you have an idea about this error.

**Comment by jimmywarting** [comment]
Do you have a minimal html example also?
dose this only happens in iOS?

**Comment by f0rmat1k** [comment]
when user are submitting form i load polyfill first:
```js
async handleFormSubmit(e) {
	    e.preventDefault();

	    await this.loadPolyfill(); // this moment error occurs 
            const formData = new FormData(this.form);
   // ...
}

async loadPolyfill() {
     if (typeof FormData === 'undefined' || !FormData.prototype.keys) {
            await import('formdata-polyfill'); 
     }
}
```

Yes it always happens at ios 10.3.3/Chrome 70

**Comment by f0rmat1k** [comment]
I got such environment and couldn't repeat the problem. I don't know, why some users get this error, but i will close issue.
