### ISSUE TITLE
FormData polyfill on QTWebKit

### ISSUE THREAD

**Issue by Enum1109** [jimmywarting/FormData#64]
I'm trying to get a zip file from a application which provides WebAPI.
And before display the contents of the zip file on QTWeb, unzip the file in the memory.
To realize the function above, I did by two steps as below:

 1. Download the zip file to the memory.
 2. Unzip the file and display it to the client browser.
 
 At the first step,
 On chrome, it turns out the results expected.
 But on QtWebKit, errors  occurred.
Codes as belows:
```js
var blobData = new Blob([buffer], {type: 'application/x-zip-compressed'});
blobData.lastModifiedDate = new Date();
var formData = new FormData();
formData.append("fileOBJ",blobData,fileName);
var fileOBJ = formData.get("fileOBJ");
```
And errors as belows:
`TypeError: undefined is not a constructor (evaluating 'formData.get(\"fileOBJ\")')`
Is there any alternative method for formData.get() to solve this problem?

**Comment by jimmywarting** [comment]
When you call method `formData.get` it will try to normalize the value 

```js
return map[name] ? normalizeValue(map[name][0]) : null
```

https://github.com/jimmywarting/FormData/blob/f18bd6e8dbea9e520cdd0d98f539c520a236cee0/FormData.js#L69-L79

The probable cause is that the [window.File](https://developer.mozilla.org/en-US/docs/Web/API/File) is not a constructor 

I try to work around it by using Blob as a fallback and also assign File to `window` but for some reason it don't seem to do so for you..?

https://github.com/jimmywarting/FormData/blob/f18bd6e8dbea9e520cdd0d98f539c520a236cee0/FormData.js#L34-L67

Could you try if File constructor exist in QTWebKit and maybe investigate why it aint able to set a tiny Blob polyfill to the global `window`?

**Comment by Enum1109** [comment]
Thank you for the reply.
Unfortunately, File constructor doesn't exist in QTWebKit.

**Comment by jimmywarting** [comment]
> Unfortunately, File constructor doesn't exist in QTWebKit.

Not sure why this line does not work...
```js
   global.File = function(b, d, c) {...}
```

Think that is something you need to figure out first.

**Comment by Enum1109** [comment]
Thank you for your prompt response. I'll keep digging......
