### ISSUE TITLE
new URLSearchParams(formData) support

### ISSUE THREAD

**Issue by glebm** [jimmywarting/FormData#75]
For browsers that support `URLSearchParams` (Edge), the polyfill doesn't work as the constructor argument:

```javascript
new URLSearchParams(new FormData(formElement)).toString() // => ""
```

This works:

```javascript
new URLSearchParams(new FormData(formElement).entries()).toString()
```

Perhaps this polyfill should patch the `URLSearchParams` constructor?

**Comment by jimmywarting** [comment]
Not sure we should patch each and everything that use the FormData. it's more up to everything else to use it correctly 

another thing that works:

```js
new URLSearchParams(...new FormData(formElement)).toString()
```

**Comment by glebm** [comment]
Sorry, neither `...` nor entries actually work.

```js
var f = new FormData();
f.append('x', '1');

new URLSearchParams(...f).toString()
// Invalid argument

new URLSearchParams(f.entries()).toString()
// "next=function+(b){return+a.h(b)}&throw=function+(b){return+a.i(b)}&return=function+(b){return+K(a,b)}"
```

**Comment by glebm** [comment]
Basically Edge does not treat the argument as a `sequence` (as per the spec), so the bug is in the Edge implementation of `URLSearchParams`. This polyfill implements `Iterator.symbol` etc correctly.

There is a polyfill for `URLSearchParams`:

https://github.com/ungap/url-search-params

**Comment by jimmywarting** [comment]
Need to correct myself... this was wrong of me:
```js
new URLSearchParams(...f).toString()
```
should actually be:
```js
new URLSearchParams([...f]).toString()
```
