### ISSUE TITLE
minification issue with uglify

### ISSUE THREAD

**Issue by jony89** [jimmywarting/FormData#8]
when compiling with uglify I get : 

ERROR in 1.chunk.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [1.chunk.js:7515,15]

because of the line : 

```js
	const wm = o => map.get(o)
```

This is because the file is not transpiled, so i had to add this module so babel will transpile it during build, i think you should satisfy es5 script as the main script (compiled) and use js:next for the es6 code. 

Also test minification of mode as stand alone.

**Comment by garrensweet** [comment]
@jony89  What module did you use to get this to work?

**Comment by jony89** [comment]
u didn't get me, usually you are not supposed to transpile modules in node_modules folder, or at least not specifying this, but with this one I had to, so I specifically specify this module( in webpack confguration for example) so babel will transpile it as well, because it's main script is ES6.

**Comment by reescott** [comment]
Any update on getting this to work with uglify in webpack @jimmywarting?

**Comment by jimmywarting** [comment]
I put a minified version up on npm from closure compiler that is now used by default
