### ISSUE TITLE
MS Edge now uses native version for FormData.getAll

### ISSUE THREAD

**Issue by Laslo89** [jimmywarting/FormData#80]
Hi @jimmywarting,
I just updated MS Edge to version 44.17763.1.0. It seems that the browser uses its own version of getAll. Unfortunately it is broken. At least it returns no array, as it should do.

Can you implement a check which checks for the useragent and Ignore the native Version of FormData in Edge? Like so for example:
```
if("function"===typeof Blob&&("undefined"===typeof FormData||!FormData.prototype.keys || window.navigator.userAgent.indexOf("Edge") > -1) {
  ... overwrite native code
}
```

**Comment by jimmywarting** [comment]
Would like to avoid doing UA-sniffing.
rather want to do feature detecting... what dose getAll return instead? an iterator?

**Comment by Laslo89** [comment]
I created a codepen to explain what I mean. https://codepen.io/anon/pen/BbvZPO
It seems like getAll works fine, if you use the first element name of a form as key. if you use the second element name it breaks with the error message

```
Could not complete the operation due to error 80020101.
```

**Comment by jeffal** [comment]
Stalebot please keep this issue open.

**Comment by stanhu** [comment]
On Microsoft Edge 44.18.18362 (with a user Agent string of Edge/18362), the results of `getAll()` are wrong for elements after the first. Notice the first element of the array is `null` when it should be omitted.

![image](https://user-images.githubusercontent.com/963826/67818968-6e943a80-fa70-11e9-9b0c-aa7cbb9eb107.png)

**Comment by stanhu** [comment]
I've reported this bug to Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/23856020/
