### ISSUE TITLE
Parse error in IE11 @ v3.0.17 

### ISSUE THREAD

**Issue by ruimarques** [jimmywarting/FormData#85]
This line looks weird (?) and causes me an error in IE11:

https://github.com/jimmywarting/FormData/blame/b54e8b498fbf7e469580af01b362790cee648fff/FormData.js#L54

**Error:**

`SCRIPT1003: Expected ':'`

Seems somehow adding a space in `value ()` fix some bug in node but a regression for ie11. But just speculating here.

**Comment by jimmywarting** [comment]
Use the compiled minified version?

**Comment by ruimarques** [comment]
Ah didn't realise two versions where shipped. 
Was importing `import 'formdata-polyfill/FormData';` instead of ` import 'formdata-polyfill';` which works correctly.
