### ISSUE TITLE
File object is missing webkitRelativePath attribute

### ISSUE THREAD

**Issue by joshuaob** [jimmywarting/FormData#92]
Currently, the file object returned using form data polyfill is missing the webkitRelativePath attribute on Microsoft edge browser. 

https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath

**Comment by jimmywarting** [comment]
> Non-standard
This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

**Comment by jimmywarting** [comment]
besides, what dose relative path has anything to do with FormData?
