### ISSUE TITLE
IE sets Content-Type to application/json

### ISSUE THREAD

**Issue by murali101002** [jimmywarting/FormData#93]
IE11 doesn't recognize the mime type of formData and sets Content-Type to application/json instead of multipart/form-data.
Note: This is a duplicate of #61 
Request Headers and Code posted below

![image](https://user-images.githubusercontent.com/15885640/62320410-1bf5b300-b46e-11e9-8d67-5c05639210cc.png)

![image](https://user-images.githubusercontent.com/15885640/62320537-6a0ab680-b46e-11e9-80b1-c04088d31df1.png)

**Comment by jimmywarting** [comment]
It dose not feel right that it would default it to application/json unless you are using something like an ajax library that sets the `content-type` for you.
it could be that the ajax lib that you are using isn't recognizing that the polyfill and it is not equal to native FormData and therefore sets the content-type to application/json cuz the polyfilled formdata looks like an object?

1) How are you loading the formdata polyfill + the ajax library? is the pollyfill loaded first?
2) what ajax lib are you using? angulars http? jQuery ajax? request? axois?
3) I know fetch isn't implemented in IE11 so could could you try using just regular `XMLHttpRequest` and test it?

```js
var fd = new FormData()
var xhr = new XMLHttpRequest()
fd.append('x', 'y')
xhr.open('POST', 'https://httpbin.org/post')
xhr.send(fd)
xhr.onload = function() {
  console.log(xhr.response)
}
```

4) could you maybe do a fiddle where you break it down to the minimal reproducible code?

**Comment by jimmywarting** [comment]
never mind, i see now that you use angulars http stuff

**Comment by murali101002** [comment]
Thanks for the quick response. I am working on VM. I tried to reproduce the same on stackblitz on my local machine and it works perfectly fine. The very same request sets Content-Type to multipart/form-data on chrome on VM. But fails on IE. And yes, I am loading the polyfill first just like in the README

**Comment by jimmywarting** [comment]
I don't have IE, or any VM. only running Mac, so a bit hard for me to test it.

I have only used angular 1.x back in the days but i was looking into how angular sets the content type.

https://github.com/angular/angular/blob/f2d47c96c45edcb87f9fd53f06c4250e4d0479cd/packages/common/http/src/request.ts#L59-L66

```ts
/**
 * Safely assert whether the given value is a FormData instance.
 *
 * In some execution environments FormData is not defined.
 */
function isFormData(value: any): value is FormData {
  return typeof FormData !== 'undefined' && value instanceof FormData;
}
```

and also a bit of how `detectContentTypeHeader` dose... the last fallback is to use application/json it seems

what is the result of running this yourself in IE?
```js
console.log(typeof FormData !== 'undefined' && value instanceof FormData)
```

if you somehow could add a breakpoint to angulars http client and debunk it it would be useful to know what makes angular not recognize the formdata polyfill
https://github.com/angular/angular/blob/5ae9b76a9b8618ebe0e734532c576e6d38ba72cd/packages/common/http/src/xhr.ts#L100

**Comment by jimmywarting** [comment]
oh, btw the polyfill dose not even load (replace) the native formdata in chrome cuz chrome has everything

to test the polyfill in chrome you would have to `delete window.FormData` before loading the polyfill

**Comment by murali101002** [comment]
Let me implement and let you know.

**Comment by jimmywarting** [comment]
how is it working out for you?

**Comment by wata-lb** [comment]
@murali101002 

I'm getting similar errors(express server can not get any form data).

Environment are IE11(win7/10) with core-js@^2.6.6 .
(core-js@^2.6.6 are depends on babel-polyfill@6 or babel-runtime@6 ).

Probably, core-js@2.6.6 has IE8 changes or enum changes. formdata-polyfill is affected these changes. 
Try edit package-lock.json or yarn.lock, use core-js@2.6.5.

**Comment by murali101002** [comment]
@jimmywarting no luck. anyway we got new requirement to upload files to s3. still curious on this. probably the issue might be the firewall configuration on the vm

**Comment by murali101002** [comment]
@wata-lb did the issue got resolved for you? the polyfill works fine on my local machine. I have issues only on the VM
